batch_size: 4
workers: 8
img_size: 128
iterations: 80000
log_iter: 20
tensorboard_log_interval: 500
print_log_interval: 1000
continue_iter: 0  # continue from a ckeckpoint that has run for n iteration  (0 if a new run)
latent_dim: 1024
data_dir: '../data/complete_dataset_ppy/'
log_dir: 'logs'
experiment_name: 'code_test_complete_dataset'
fold: 0  # fold number for cross validation
num_class: 0
lambda_class: 0.1  # 'weights for the auxiliary classifier loss')
save_model_interval: 20000
start_model_saving: 20000
network:
  generator_learning_rate: 0.0001
  generator_passes_per_iteration: 1  # number of generator pass per iteration
  discriminator_learning_rate: 0.0004
  encoder_learning_rate: 0.0001
cluster_enabled: False
