training:
  epochs: 10
dataloader:
  batch_size: 1
  samples_per_epoch: 1
augmentations:
  gaussian_noise:
    enabled: True
    sigma: 2
images:
  shape: [ 15,15,6 ] #Shape of the concatenated images used by the network
network:
  architecture: 'vanilla' #wasserstein, wasserstein_gp or vanilla
  generator:
    optimizer:
      learning_rate: 0.0002
  discriminator:
    gradient_penalty_weight: 5
    clip_value: 0.01
    optimizer:
      learning_rate: 0.0001
hpo: False
inference:
  enabled: True
  architecture: 'vanilla'
  checkpoint_path: 'checkpoints/example'
cluster:
  enabled: False
