experiment_name: 'test'
data_dir: 'data/npy/concatenated/'
img_size: 128
iterations: 5
upload_results: True
generate_results_on_completion: True
generate_n_samples: 3
tensorboard_log_interval: 100
print_log_interval: 100
latent_dim: 1024
save_model_interval: 2
start_model_saving: 1
workers: 8
continue_iter: 0
batch_size: 4
lambda_class: 0.1  # 'weights for the auxiliary classifier loss')
num_class: 0
fold: 0
log_dir: 'logs'
network:
  generator_learning_rate: 0.0001
  generator_passes_per_iteration: 1
  discriminator_learning_rate: 0.0004
  encoder_learning_rate: 0.0001
cluster_enabled: False
shuffle: True
augmentation:
  input_dir: '../data/cropped_original'
  output_dir: '../data/augmented'
  images_only: False
  normalize: True
  reorient: False
  random_affine: False
  rotate: False
  translate: False
  elastic_deform: False
  flip: False
  smooth_gaussian: False
  rotate90: False