batch_size: 4
workers: 8
img_size: 256
iterations: 80000
tensorboard_log_interval: 100
print_log_interval: 100
continue_iter: 0  # continue from a ckeckpoint that has run for n iteration  (0 if a new run)
latent_dim: 1024
data_dir: 'data/npy/256/'
log_dir: 'logs'
experiment_name: '256_concat_y_axis'
fold: 0  # fold number for cross validation
num_class: 0
lambda_class: 0.1  # 'weights for the auxiliary classifier loss')
save_model_interval: 20000
start_model_saving: 20000
network:
  generator_learning_rate: 0.0001
  generator_passes_per_iteration: 1  # number of generator pass per iteration
  discriminator_learning_rate: 0.0004
  encoder_learning_rate: 0.0001
cluster_enabled: False
shuffle: True
augmentation:
  input_dir: '../data/cropped_original'
  output_dir: '../data/augmented'
  images_only: False
  normalize: True
  reorient: False
  random_affine: False
  rotate: False
  translate: False
  elastic_deform: False
  flip: False
  smooth_gaussian: False
  rotate90: False