experiment_name: '256_binary'
data_dir: 'data/npy/256_binary/'
img_size: 256
iterations: 80000
upload_results: True
generate_results_on_completion: False
generate_n_samples: 3
tensorboard_log_interval: 100
print_log_interval: 100
latent_dim: 1024
save_model_interval: 20000
start_model_saving: 60000
workers: 8
continue_iter: 0
batch_size: 4
lambda_class: 0.1  # 'weights for the auxiliary classifier loss')
num_class: 0
fold: 0
log_dir: 'logs'
hpo: False
preprocessing:
  enabled: True
  img_input_dir: 'data/cropped_original/images/'
  mask_input_dir: 'data/cropped_original/masks/'
  output_dir: 'data/npy/256_binary/'
  num_jobs: 8
  low_threshold: -1024
  high_threshold: 600
  img_size: 256
network:
  generator_learning_rate: 0.0002
  generator_passes_per_iteration: 1
  discriminator_learning_rate: 0.0004
  encoder_learning_rate: 0.0002
cluster_enabled: False
shuffle: True
augmentation:
  input_dir: '../data/cropped_original'
  output_dir: '../data/augmented'
  images_only: False
  normalize: False
  reorient: False
  random_affine: False
  rotate: False
  translate: False
  elastic_deform: True
  flip: False
  smooth_gaussian: True
  rotate90: False