training:
  epochs: 20
dataloader:
  batch_size: 1
  limit: 3
images:
  shape: [ 154,154,54 ] #Shape of the concatenated images used by the network
network:
  generator:
    optimizer:
      learning_rate: 0.0001
  discriminator:
    optimizer:
      learning_rate: 0.0001
cluster:
  enabled: False