training:
  epochs: 20
dataloader:
  batch_size: 1
  limit: 3
images:
  shape: [ 16,16,32 ] #Shape of the concatenated images used by the network
  padded_shape: [ 16,16,16 ] #Shape of individual images to be padded
network:
  generator:
    optimizer:
      learning_rate: 0.0001
  discriminator:
    optimizer:
      learning_rate: 0.0001
cluster:
  enabled: False