training:
  epochs: 1000
dataloader:
  batch_size: 1
  samples_per_epoch: 10
images:
  shape: [ 154,154,54 ] #Shape of the concatenated images used by the network
network:
  architecture: 'wasserstein' #wasserstein, wasserstein_gp or vanilla
  generator:
    optimizer:
      learning_rate: 0.0002
  discriminator:
    gradient_penalty_weight: 5
    clip_value: 0.01
    optimizer:
      learning_rate: 0.0001
cluster:
  enabled: False